# Generated by Django 6.0 on 2025-12-12 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Kelas')),
                ('description', models.TextField(verbose_name='Deskripsi Singkat')),
                ('course_code', models.CharField(max_length=10, unique=True, verbose_name='Kode Kursus')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('nama_lengkap', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, default='Pelajar Aktif', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('total_waktu_belajar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Waktu Belajar (Jam)')),
                ('nilai_rata_rata', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nilai Rata-rata Kuis')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Persentase Progres')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diakses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alp_app.course', verbose_name='Kelas yang Diikuti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
