# Generated by Django 6.0 on 2025-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0002_course_userprofile_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perubahan_waktu_belajar',
            field=models.CharField(default='↑ 0%', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pesan_nilai_rata_rata',
            field=models.CharField(default='Performa stabil', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pesan_waktu_belajar',
            field=models.CharField(default='dari Minggu Lalu', max_length=50),
        ),
    ]
