# Generated by Django 6.0 on 2025-12-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0003_userprofile_perubahan_waktu_belajar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
