# Generated by Django 6.0 on 2025-12-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0007_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alp_app.quiz', verbose_name='Quiz yang diselesaikan'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='Total Pertanyaan'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(verbose_name='Skor Benar'),
        ),
    ]
