# Generated by Django 6.0 on 2025-12-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0009_lessoncompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'content_type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='alp_app.lesson', verbose_name='Terkait dengan Pelajaran'),
        ),
    ]
