# Generated by Django 6.0 on 2025-12-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0010_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncompletion',
            options={},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Isi Materi / Deskripsi'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Contoh: https://www.youtube.com/embed/...', null=True, verbose_name='URL Video YouTube'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alp_app.quiz'),
        ),
    ]
