# Generated by Django 6.0 on 2025-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0011_alter_lessoncompletion_options_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.FloatField(default=0.0, help_text='Gunakan nilai antara -3.0 (mudah) hingga +3.0 (sulit). 0.0 adalah tingkat kesulitan rata-rata.', verbose_name='Tingkat Kesulitan (Beta)'),
        ),
    ]
