# Generated by Django 5.2.2 on 2025-12-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0013_quizresult_theta_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Umum', help_text='Contoh: Aljabar, Struktur Kalimat, Geometri, dll. Digunakan untuk saran belajar jika jawaban salah.', max_length=100, verbose_name='Topik/Pokok Materi'),
        ),
    ]
