# Generated by Django 5.2.2 on 2025-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0014_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
