# Generated by Django 5.2.2 on 2026-01-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0016_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='lesson',
        ),
        migrations.AddField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='alp_app.course'),
            preserve_default=False,
        ),
    ]
