# Generated by Django 5.2.2 on 2026-01-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0017_remove_discussion_lesson_discussion_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='alp_app.discussion'),
        ),
    ]
