# Generated by Django 6.0 on 2026-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0019_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Lanjut', 'Lanjut')], default='Dasar', max_length=20),
        ),
    ]
