# Generated by Django 6.0 on 2026-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0020_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/images/', verbose_name='Gambar Materi'),
        ),
    ]
