# Generated by Django 5.2.2 on 2026-01-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0022_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
