# Generated by Django 5.2.2 on 2026-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0024_discussion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_quiz',
            field=models.BooleanField(default=False, help_text='Centang jika materi ini adalah Kuis'),
        ),
    ]
