# Generated by Django 5.2.2 on 2026-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0025_lesson_is_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_quiz',
            field=models.BooleanField(default=True),
        ),
    ]
