# Generated by Django 5.2.2 on 2026-02-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0026_quiz_is_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_quiz',
        ),
    ]
