# Generated by Django 5.2.2 on 2026-02-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0027_remove_lesson_is_quiz_remove_quiz_is_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_quiz',
            field=models.BooleanField(default=False, help_text='Centang jika materi ini adalah Kuis'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_quiz',
            field=models.BooleanField(default=True),
        ),
    ]
