# Generated by Django 5.2.2 on 2026-02-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0028_lesson_is_quiz_quiz_is_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kategori', models.CharField(max_length=50)),
                ('pesan', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
