# Generated by Django 5.2.2 on 2026-02-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0029_supportticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportTicket',
            new_name='SupportReport',
        ),
        migrations.AlterModelOptions(
            name='supportreport',
            options={'verbose_name': 'Support Report', 'verbose_name_plural': 'Support Reports'},
        ),
    ]
