# Generated by Django 5.2.2 on 2026-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0030_rename_supportticket_supportreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
