# Generated by Django 6.0 on 2026-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp_app', '0031_alter_quizresult_date_alter_studysession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Pending', max_length=20),
        ),
    ]
