# Generated by Django 5.2.2 on 2026-02-17 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alp_app', '0028_lesson_is_quiz_quiz_is_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Materi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video & Teks'), ('ARTICLE', 'Artikel Murni'), ('QUIZ', 'Kuis Interaktif'), ('HYBRID', 'Mix (Video + Artikel + Kuis)')], default='VIDEO', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True)),
                ('video_id', models.CharField(blank=True, help_text='ID Youtube saja (misal: dQw4w9WgXcQ)', max_length=100)),
                ('body_text', models.TextField(blank=True, verbose_name='Isi Artikel (HTML)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='manager/thumbs/')),
                ('quiz_data', models.JSONField(blank=True, help_text="Format: {'questions': [...], 'timer': 60}", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='alp_app.module')),
            ],
            options={
                'verbose_name': 'Master Materi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WordImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('raw_json_result', models.JSONField(null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
