# Generated by Django 6.0 on 2025-12-12 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('nama_lengkap', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, default='Pelajar Aktif', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('total_waktu_belajar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Waktu Belajar (Jam)')),
                ('nilai_rata_rata', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nilai Rata-rata Kuis')),
                ('perubahan_waktu_belajar', models.CharField(default='↑ 0%', max_length=10)),
                ('pesan_waktu_belajar', models.CharField(default='dari Minggu Lalu', max_length=50)),
                ('pesan_nilai_rata_rata', models.CharField(default='Performa stabil', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
