# Generated by Django 6.0 on 2026-04-08 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(blank=True, choices=[('smp1', 'Kelas 7 (SMP 1)'), ('smp2', 'Kelas 8 (SMP 2)'), ('smp3', 'Kelas 9 (SMP 3)'), ('sma1', 'Kelas 10 (SMA 1)'), ('sma2', 'Kelas 11 (SMA 2)'), ('sma3', 'Kelas 12 (SMA 3)')], max_length=20, null=True, verbose_name='Kelas Akademik')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('nama_lengkap', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, default='Pelajar Aktif', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('ability_score', models.FloatField(default=0.0, help_text='Estimasi kemampuan siswa berdasarkan Model Rasch (IRT)', verbose_name='Skor Kemampuan (Theta)')),
                ('total_waktu_belajar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Waktu Belajar (Jam)')),
                ('nilai_rata_rata', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nilai Rata-rata Kuis')),
                ('points', models.IntegerField(default=0, verbose_name='Poin Belajar')),
                ('perubahan_waktu_belajar', models.CharField(default='↑ 0%', max_length=10)),
                ('pesan_waktu_belajar', models.CharField(default='dari Minggu Lalu', max_length=50)),
                ('pesan_nilai_rata_rata', models.CharField(default='Performa stabil', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
