# Generated by Django 6.0 on 2025-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ability_score',
            field=models.FloatField(default=0.0, help_text='Estimasi kemampuan siswa berdasarkan Model Rasch (IRT)', verbose_name='Skor Kemampuan (Theta)'),
        ),
    ]
