# Generated by Django 5.2.2 on 2026-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_profile_kelas_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kelas',
            field=models.CharField(blank=True, choices=[('smp1', 'Kelas 7 (SMP 1)'), ('smp2', 'Kelas 8 (SMP 2)'), ('smp3', 'Kelas 9 (SMP 3)'), ('sma1', 'Kelas 10 (SMA 1)'), ('sma2', 'Kelas 11 (SMA 2)'), ('sma3', 'Kelas 12 (SMA 3)')], max_length=20, null=True, verbose_name='Kelas Akademik'),
        ),
    ]
